### ISSUE TITLE
AWS: Nixops deploy fails re-creating deleted instance

### ISSUE THREAD

**Issue by mikemole** [NixOS/nixops#418]
An instance in my nixops deployment was deleted via the AWS Console.  I ran `nixops deploy -d my-deployment-name --show-trace --allow-recreate --check --kill-obsolete --allow-reboot`. It detected the missing instance, and it launched a new one, but it failed to wait for it to come up.  It seems to be referencing the state of the previously terminated instance instead of the new one.  If I then wait for the instance to come back up, and rerun the deploy command, the deployment will continue.

```
mysql...> EC2 instance went away (state ‘terminated’), will recreate
mysql...> creating EC2 instance (AMI ‘ami-REDACTED’, type ‘m4.large’, region ‘None’)...
app....> waiting for IP address...
elasticsearch> waiting for IP address...
app....> [running] None / IPADDRESS
app....> waiting for SSH...
elasticsearch> [running] None / IPADDRESS
elasticsearch> waiting for SSH...
mysql...> waiting for IP address... [terminated] error: EC2 instance ‘i-NEW-INSTANCE-ID’ failed to start (state is ‘terminated’)
```

**Comment by rbvermaa** [comment]
I think this is already fixed. I hope to release nixops 1.4 next week, which should include the fix.

**Comment by mimar-ciklum** [comment]
The issue still persists with 1.5.2, however it seems that running the command twice or thrice solves the problem - both terminated and new instances are present in console.
